# Generated by Django 5.0 on 2023-12-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='programming_language',
            field=models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('java', 'Java'), ('c#', 'C#')], max_length=20),
        ),
    ]
