# Generated by Django 5.0 on 2023-12-08 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_programming_language'),
        ('task', '0002_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_list', to='students.student'),
        ),
        migrations.AddField(
            model_name='task',
            name='views_by',
            field=models.ManyToManyField(blank=True, related_name='task_view', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
